module.exports = [
  {
    id: 'dia-de-los-muertos',
    name: 'Dia de los Muertos',
    description: 'Mexican Day of the Dead Celebration',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1509003989671-2b1ce38b470d?w=400',
    prompt: 'Transform this room into a vibrant Mexican Dia de los Muertos celebration chamber, with brilliant orange marigold flowers carpeting every surface, hand-painted sugar skull decorations lining shelves, flickering votive candles illuminating a colorful ofrenda altar adorned with framed photos, and papel picado banners in purple and gold strung across the ceiling',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'bollywood-palace',
    name: 'Bollywood Palace',
    description: 'Opulent Indian Film Set',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400',
    prompt: 'Transform this room into an opulent Bollywood palace film set, with intricately carved white marble jali screens filtering golden light, sweeping silk drapes in deep emerald and ruby jewel tones, lotus flower motifs on every arch, dazzling mirror inlay work on pillars, and lavish gold leaf detailing across ornate ceilings and grand doorways',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'kpop-studio',
    name: 'K-Pop Studio',
    description: 'Modern Korean Entertainment Studio',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400',
    prompt: 'Transform this room into a cutting-edge K-Pop entertainment studio, with programmable LED light panels cycling through pink and cyan hues, professional sound-proof padded walls, sleek minimalist white and black furniture, neon purple accent strip lighting along edges, a glass-walled recording booth with premium microphones, and glossy reflective flooring',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'arabian-nights-palace',
    name: 'Arabian Nights Palace',
    description: "Scheherazade's Storytelling Chamber",
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=400',
    prompt: 'Transform this room into Scheherazade\'s enchanted storytelling chamber from Arabian Nights, with jewel-encrusted silk cushions scattered on Persian rugs, hanging brass lanterns with star and crescent cutouts casting intricate shadow patterns, a billowing silk canopy overhead in deep sapphire, elaborate mosaic tile walls, and wisps of sandalwood incense smoke curling through the air',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'polynesian-longhouse',
    name: 'Polynesian Longhouse',
    description: 'Pacific Island Meeting House',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=400',
    prompt: 'Transform this room into a traditional Polynesian longhouse meeting hall, with towering carved tiki totems flanking the entrance, a soaring woven palm frond roof revealing slivers of tropical sky, tapa cloth walls decorated with ancestral geometric patterns, polished driftwood benches, shell and bone carvings, and a warm ocean breeze carrying the scent of salt and plumeria',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'tibetan-monastery',
    name: 'Tibetan Monastery',
    description: 'High-Altitude Buddhist Sanctuary',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1567591414240-e9c1e838bb0d?w=400',
    prompt: 'Transform this room into a serene Tibetan Buddhist monastery perched high in the Himalayas, with rows of spinning brass prayer wheels along the walls, vibrant thangka paintings depicting mandalas in rich reds and golds, flickering butter lamp offerings on a low altar, deeply carved wooden columns painted in vermillion, and vast snow-capped mountain peaks visible through open windows',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'celtic-druid-grove',
    name: 'Celtic Druid Grove',
    description: 'Ancient Sacred Grove Temple',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=400',
    prompt: 'Transform this room into an ancient Celtic druid sacred grove temple, with a ring of weathered standing stones encircling a central ceremonial fire pit, bundles of mistletoe hanging from massive gnarled oak root walls, thick emerald moss covering every stone surface, rune-carved wooden totems, and an ethereal silver mist drifting through shafts of pale forest light',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'persian-tea-house',
    name: 'Persian Tea House',
    description: 'Traditional Iranian Chai-Khaneh',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    prompt: 'Transform this room into a traditional Persian chai-khaneh tea house, with exquisite hand-painted floral tile walls in turquoise and cobalt blue, a gleaming copper samovar steaming on an ornate tray, richly patterned geometric carpets layering the floor, a cushioned raised seating platform with embroidered bolsters, and jewel-toned stained glass windows casting warm kaleidoscopic light',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'mexican-hacienda',
    name: 'Mexican Hacienda',
    description: 'Colonial Hacienda Courtyard Room',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400',
    prompt: 'Transform this room into a sun-drenched colonial Mexican hacienda courtyard room, with warm terracotta tile floors in herringbone pattern, ornate wrought iron window grilles and candelabras, hand-painted Talavera pottery in cobalt and yellow adorning niches, cascading magenta bougainvillea climbing the adobe walls, and dark hand-carved wooden ceiling beams overhead',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'balinese-temple',
    name: 'Balinese Temple',
    description: 'Hindu Balinese Temple Interior',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400',
    prompt: 'Transform this room into a sacred Hindu Balinese temple interior, with intricately carved dark volcanic stone walls depicting mythological scenes, shimmering gold leaf offerings arranged on tiered pedestals, fragrant white frangipani flowers scattered across stone floors, traditional bronze gamelan instruments resting in alcoves, spiraling incense smoke, and soft tropical light filtering through split gateway doorways',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
