module.exports = [
  {
    id: 'james-bond-villain-lair',
    name: 'James Bond Villain Lair',
    description: 'Volcanic Island Base',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1545243424-0ce743321e11?w=400',
    prompt: 'Transform this room into a James Bond villain lair inside a volcanic island fortress with raw concrete brutalism, a massive observation deck overlooking the ocean, a sunken shark tank glowing turquoise, a retractable roof revealing the crater, and a dramatic control room dominated by an illuminated world map and banks of Cold War-era monitors',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'willy-wonka-factory',
    name: 'Willy Wonka Factory',
    description: 'Chocolate River Room',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    prompt: 'Transform this room into Willy Wonka\'s chocolate factory with a flowing chocolate river winding through candy meadows, edible floral wallpaper in pastel swirls, towering candy cane columns supporting a whimsical Victorian-industrial glass ceiling, lollipop trees, gumdrop cobblestones, and warm caramel-toned light filling every sugary corner',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'titanic-first-class',
    name: 'Titanic First Class',
    description: '1912 Ocean Luxury',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=400',
    prompt: 'Transform this room into a Titanic first-class dining saloon circa 1912 with rich mahogany wall panels, sparkling crystal chandeliers, crisp white linen tablecloths set with fine china, the iconic grand staircase with wrought-iron railings and a cherub lamp, plush velvet seating, and the quiet elegance of Edwardian ocean-liner opulence',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'indiana-jones-temple',
    name: 'Indiana Jones Temple',
    description: 'Ancient Treasure Vault',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=400',
    prompt: 'Transform this room into the ancient treasure temple from Indiana Jones with a golden idol resting on a stone pedestal bathed in a shaft of light, torch-lit moss-covered corridors, carved stone walls depicting warnings, hidden booby-trap mechanisms with pressure plates, crumbling steps, cobwebs, and the amber glow of centuries-old mystery',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'tron-legacy-grid',
    name: 'Tron Legacy Grid',
    description: 'Digital Light World',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400',
    prompt: 'Transform this room into the Tron Legacy digital grid with sleek black glass surfaces illuminated by glowing electric-blue circuit lines, a light cycle garage displaying luminous vehicles, geometric floor tiles pulsing with data, a minimalist command console, and the infinite dark void of cyberspace visible through transparent walls',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'avatar-pandora-home',
    name: 'Avatar Pandora Home',
    description: 'Bioluminescent Dwelling',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=400',
    prompt: 'Transform this room into a Na\'vi dwelling inside a massive Hometree on Pandora with bioluminescent plants casting soft purple and cyan light, woven hammock beds suspended from living wood, spiraling organic architecture of roots and vines, glowing moss, translucent seed sprites drifting in the air, and a canopy opening to Pandora\'s starlit sky',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'blade-runner-market',
    name: 'Blade Runner Market',
    description: 'Cyberpunk Neon Bazaar',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400',
    prompt: 'Transform this room into the Blade Runner street market with a crowded rain-soaked Asian-inspired bazaar, flickering neon signs in Japanese and Chinese reflecting off wet pavement, steam billowing from sizzling food stalls, dense cyberpunk layering of cables and holographic ads, umbrella-clutching silhouettes, and moody amber-and-magenta haze',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: '2001-space-odyssey',
    name: '2001 Space Odyssey',
    description: 'Discovery One Interior',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400',
    prompt: 'Transform this room into the Discovery One centrifuge from 2001: A Space Odyssey with pristine white curved corridors bending upward, the glowing red eye of HAL 9000 set into a console panel, retro-futuristic 1960s space design with padded walls, clinical lighting, geometric furniture, and the eerie silence of deep-space isolation',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'narcos-drug-lord-mansion',
    name: 'Narcos Drug Lord Mansion',
    description: 'Hacienda of Excess',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400',
    prompt: 'Transform this room into a Pablo Escobar-style narco mansion with excessive gold-plated fixtures, a lush tropical courtyard with towering palm trees and a turquoise pool, white marble floors, gaudy 1980s luxury furnishings, mirrored ceilings, oversized leather sofas, and the ostentatious extravagance of cartel wealth at its peak',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'sherlock-holmes-study',
    name: 'Sherlock Holmes Study',
    description: '221B Baker Street',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400',
    prompt: 'Transform this room into Sherlock Holmes\' study at 221B Baker Street with Victorian clutter of case files and newspaper clippings pinned to walls, a bubbling chemistry set on the desk, a violin resting on an armchair by the crackling fireplace, Persian slipper tobacco pouch, dense fog visible through lace-curtained windows, and gaslight warmth',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
