module.exports = [
  {
    id: 'witcher-kaer-morhen',
    name: 'The Witcher Kaer Morhen',
    description: 'Wolf School Fortress',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=400',
    prompt: 'Transform this room into the Kaer Morhen fortress training hall from The Witcher, featuring massive stone walls with wolf school medallion carvings, iron weapon racks lined with silver swords, a roaring great fireplace casting warm amber light, heavy timber ceiling beams, leather-bound combat dummies, and worn stone floors marked by centuries of witcher training',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'mandalorian-razor-crest',
    name: 'Mandalorian Razor Crest',
    description: 'Bounty Hunter Ship',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=400',
    prompt: 'Transform this room into the interior of the Razor Crest from The Mandalorian, a worn and battle-scarred bounty hunter gunship with a carbonite freezing chamber along the wall, a locked weapon locker filled with beskar gear, exposed wiring and riveted durasteel panels, Grogu\'s small hammock cradle in the corner, dim cockpit lighting with orange instrument glow',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'squid-game-dormitory',
    name: 'Squid Game Dormitory',
    description: 'Numbered Bunk Beds',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400',
    prompt: 'Transform this room into the Squid Game player dormitory, a massive industrial warehouse filled with stacked metal bunk beds numbered in the hundreds, oppressive mint-green painted concrete walls, harsh overhead fluorescent tube lighting casting sterile white glow, players in numbered teal tracksuits, surveillance cameras in every corner, and a central staircase leading nowhere',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'last-of-us-shelter',
    name: 'The Last of Us Shelter',
    description: 'Post-Apocalyptic Safe House',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400',
    prompt: 'Transform this room into a Last of Us post-apocalyptic safe house, crumbling concrete walls with vines and moss creeping through cracks, nature aggressively reclaiming the structure, makeshift wooden barricades and boarded windows, warm firelight from a barrel fire, scattered survival supplies, a worn mattress on the floor, broken ceiling revealing overgrown trees above',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'succession-roy-penthouse',
    name: 'Succession Penthouse',
    description: 'Billionaire Cold Luxury',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    prompt: 'Transform this room into the Roy family Manhattan penthouse from Succession, ultra-minimalist cold modern luxury with floor-to-ceiling windows overlooking the New York skyline, stark contemporary art on white walls, Italian marble floors, designer furniture with sharp geometric lines, muted gray and cream palette, a massive open-plan living space radiating ruthless wealth and emotional emptiness',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'bridgerton-ballroom',
    name: 'Bridgerton Ballroom',
    description: 'Regency-Era Elegance',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400',
    prompt: 'Transform this room into the Bridgerton Regency-era ballroom, a grand palatial hall with towering crystal chandeliers dripping with candles, ornate gold leaf crown moldings, polished parquet dance floor, pastel floral arrangements of wisteria and peonies on marble pedestals, silk draped windows in soft lavender and cream, string quartet alcove, and soft romantic candlelight',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'vikings-great-hall',
    name: 'Vikings Great Hall',
    description: 'Norse Mead Hall',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=400',
    prompt: 'Transform this room into a Viking great hall Norse longhouse from the show Vikings, massive rough-hewn timber beams supporting a cathedral-height roof, a roaring central fire pit with iron cauldron, animal pelts draped over carved wooden thrones, intricate dragon carvings on pillars, shields and axes mounted on walls, long feasting tables with mead horns, smoky atmosphere with flickering torchlight',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'the-crown-buckingham',
    name: 'The Crown Buckingham',
    description: 'Royal State Room',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400',
    prompt: 'Transform this room into a Buckingham Palace state room from The Crown, an opulent gilded ceiling with painted frescoes, crimson red carpeting stretching wall to wall, a towering crystal chandelier with hundreds of lights, gold-framed royal portrait gallery, ornate white and gold moldings, velvet upholstered furniture, polished marble columns, and grand ceremonial grandeur',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'dark-netflix-bunker',
    name: 'Dark Netflix Bunker',
    description: 'Time Travel Bunker',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400',
    prompt: 'Transform this room into the time travel bunker from the Netflix series Dark, claustrophobic concrete walls completely covered in handwritten timeline charts and red string connections, dim amber lighting from old desk lamps, 1980s era computer monitors and analog equipment, a mysterious brass time machine apparatus in the center, worn notebooks stacked on metal shelving, eerie yellow-green atmospheric haze',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'westworld-saloon',
    name: 'Westworld Saloon',
    description: 'Wild West Meets Future',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400',
    prompt: 'Transform this room into the Mariposa Saloon from Westworld, a dusty Wild West saloon with swinging wooden doors, a polished mahogany whiskey bar lined with amber bottles, a self-playing player piano, period oil lamps and brass fixtures, but with subtle futuristic undertones — faintly glowing seams in the wood, too-perfect symmetry hinting at artificial construction, warm golden dust-filtered sunlight',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
