const worlds = [
  // ============ HISTORICAL — ICONIC HISTORICAL INTERIORS ============
  {
    id: 'aztec-temple-interior',
    name: 'Aztec Temple Interior',
    description: 'Sacred Aztec Temple Chamber',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=400',
    prompt: 'Transform this room into a sacred Aztec temple chamber with obsidian mirrors reflecting torch flames, a golden sun disk on the carved stone altar wall, feathered serpent Quetzalcoatl carvings spiraling up basalt columns, copal incense smoke drifting through ceiling light shafts, jaguar pelts draped over stone benches, turquoise mosaic skull masks in wall niches, and blood-red painted glyphs',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'chinese-imperial-palace',
    name: 'Chinese Imperial Palace',
    description: 'Forbidden City Throne Room',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=400',
    prompt: 'Transform this room into the Forbidden City throne room with dragon-carved vermillion lacquer columns, an elevated golden throne flanked by cloisonne incense burners, ornate jade screens with landscape carvings, silk tapestries embroidered with five-clawed imperial dragons in gold thread, a coffered ceiling painted with celestial cloud motifs, and warm amber light suffusing the opulent red and gold palette',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'samurai-castle-hall',
    name: 'Samurai Castle',
    description: 'Japanese Feudal Castle Hall',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400',
    prompt: 'Transform this room into a Japanese feudal castle reception hall with woven tatami floors edged in indigo, painted fusuma sliding doors depicting cherry blossoms and golden clouds, a raised dais with a lacquered katana display rack, warm paper lanterns casting amber glow across dark cypress beams, a tokonoma alcove with hanging scroll and ikebana, and shoji screens filtering pale daylight',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'art-nouveau-paris-salon',
    name: 'Art Nouveau Paris Salon',
    description: '1900s Parisian Salon',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=400',
    prompt: 'Transform this room into a 1900s Parisian Art Nouveau salon with Mucha-inspired organic curves in wrought-iron railings shaped like twisting vines, a stained glass lamp casting jewel-toned light across velvet settees, absinthe-green wallpaper with sinuous botanical patterns, a marble-topped cafe table with crystal glasses, tall windows revealing gas-lit boulevards, gilded peacock ceiling motifs, and warm gaslight ambiance',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'alhambra-palace-room',
    name: 'Alhambra Palace',
    description: 'Moorish Palace Room',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=400',
    prompt: 'Transform this room into a Moorish Alhambra palace chamber with geometric zellige tilework in cobalt blue, emerald, and terracotta on lower walls, a honeycomb muqarnas ceiling carved from white stucco, slender arabesque columns framing arched windows overlooking a courtyard fountain, Islamic calligraphy bands in gold leaf along carved plaster friezes, and dappled sunlight filtering through mashrabiya lattice screens',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'byzantine-hagia-sophia',
    name: 'Byzantine Hagia Sophia',
    description: 'Golden Mosaic Interior',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=400',
    prompt: 'Transform this room into the Byzantine interior of Hagia Sophia with a soaring dome pierced by arched windows flooding the space with divine light, shimmering gold mosaic tesserae depicting saints and seraphim, massive marble columns in green and porphyry purple supporting sweeping arches, hanging oil lamps on chains swaying through incense-hazed air, and a luminous golden atmosphere where heaven and earth merge',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'tudor-english-manor',
    name: 'Tudor English Manor',
    description: 'Henry VIII Era Great Hall',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1513584684374-8bab748fbf90?w=400',
    prompt: 'Transform this room into a Tudor-era English great hall with a hammer-beam oak ceiling, heraldic tapestries displaying lions rampant on stone walls, a long oak table set with pewter goblets, a roaring fire in a stone fireplace carved with the Tudor rose, leaded glass windows casting diamond-patterned light across rushes on flagstone floors, and iron candelabras with beeswax candles',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'baroque-vienna-salon',
    name: 'Baroque Vienna Salon',
    description: 'Schönbrunn Palace Music Room',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=400',
    prompt: 'Transform this room into a Schönbrunn Palace baroque music room with rococo gold leaf curling across pastel rose and powder blue walls, a painted ceiling fresco of allegorical figures among clouds, an ornate gilded harpsichord on intricate parquet marquetry, towering mirrors in carved gold frames multiplying crystal chandelier light, silk damask chairs, and tall arched windows draped in cream brocade',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'colonial-american-parlor',
    name: 'Colonial American Parlor',
    description: '1770s Williamsburg Parlor',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400',
    prompt: 'Transform this room into a 1770s Colonial Williamsburg parlor with Windsor chairs around a brick fireplace, a musket and powder horn above the mantel, wide-plank pine floors worn smooth, pewter candlesticks casting flickering light across a writing desk with quill and inkwell, small-paned leaded glass windows with linen curtains, whitewashed walls with dark wainscoting, and a spinning wheel in the corner',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'ancient-petra-chamber',
    name: 'Ancient Petra Chamber',
    description: 'Nabataean Treasury Interior',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=400',
    prompt: 'Transform this room into the Petra Treasury interior carved from rose-red sandstone with Nabataean columns chiseled from living rock, torch-lit niches casting amber light across walls veined in pink and salmon stone, carved reliefs depicting camel caravans and desert deities, dust motes drifting through golden light beams from the narrow entrance, and worn stone steps leading to a ceremonial platform',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];

module.exports = worlds;
