module.exports = [
  {
    id: 'howls-moving-castle',
    name: "Howl's Moving Castle",
    description: 'Magical Wizard Workshop',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400',
    prompt: 'Transform this room into the interior of Howl\'s Moving Castle, a cluttered wizard workshop with a crackling fireplace housing Calcifer, bundles of dried herbs hanging from low beams, ticking steampunk gears and pipes along the walls, scattered potion bottles, enchanted doorway dial, and warm amber lantern glow',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'attack-on-titan-hq',
    name: 'Attack on Titan HQ',
    description: 'Survey Corps Barracks',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform this room into the Survey Corps headquarters from Attack on Titan, a fortified stone military barracks with ODM gear hanging on wall racks, large tactical maps of the walls spread across wooden tables, crossed swords insignia banners, flickering lantern light casting dramatic shadows on rough stone walls',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'death-note-room',
    name: 'Death Note Room',
    description: "Light Yagami's Study",
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    prompt: 'Transform this room into Light Yagami\'s meticulous bedroom study from Death Note, a pristine Japanese student room with a neat desk, dim desk lamp casting isolated light, a hidden compartment in a drawer, a single red apple resting beside a black notebook, blinds partially drawn, and an unsettling atmosphere of calculated order',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'demon-slayer-butterfly-estate',
    name: 'Demon Slayer Butterfly Estate',
    description: 'Healing Wisteria Manor',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=400',
    prompt: 'Transform this room into the Butterfly Estate from Demon Slayer, an elegant Japanese healing manor with butterfly-motif sliding shoji screens, soft purple wisteria light filtering through windows, medicinal herb gardens visible in the courtyard, tatami floors with futon beds, and delicate butterfly ornaments adorning every surface',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'one-piece-thousand-sunny',
    name: 'One Piece Thousand Sunny',
    description: 'Straw Hat Pirate Ship',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=400',
    prompt: 'Transform this room into the interior of the Thousand Sunny from One Piece, a vibrant pirate ship with the aquarium bar glowing with tropical fish, a cozy library nook, grassy deck visible through portholes, warm polished wood walls, nautical rope details, and the joyful adventurous warmth of the Straw Hat crew',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'cowboy-bebop-lounge',
    name: 'Cowboy Bebop Lounge',
    description: 'Retro Space Jazz Ship',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400',
    prompt: 'Transform this room into the Bebop spaceship living room from Cowboy Bebop, a worn retro lounge with a beaten-up yellow couch, scattered instant noodle cups and empty cans, jazz vinyl records leaning against a turntable, 70s-style paneling, starfield visible through round ship windows, and hazy nostalgic amber lighting',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'dragon-ball-capsule-corp',
    name: 'Dragon Ball Capsule Corp',
    description: "Bulma's Futuristic Lab",
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    prompt: 'Transform this room into Bulma\'s Capsule Corporation laboratory from Dragon Ball, a bright sci-fi workshop with capsule technology pods on shelves, holographic floating displays showing schematics, scattered tools and inventions, the iconic Capsule Corp logo on the wall, blending futuristic tech with a cozy suburban Japanese home feel',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'sailor-moon-crystal-tokyo',
    name: 'Sailor Moon Crystal Tokyo',
    description: 'Crystal Palace Throne',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400',
    prompt: 'Transform this room into Neo Queen Serenity\'s crystal palace in Crystal Tokyo from Sailor Moon, with towering luminous crystal pillars refracting rainbow light, silver millennium architecture with crescent moon motifs, translucent crystal floors, ethereal moonlight pouring through faceted walls, and an aura of celestial elegance',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'ponyo-underwater',
    name: 'Ponyo Underwater',
    description: 'Magical Aquatic Home',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=400',
    prompt: 'Transform this room into the magical underwater home from Ponyo, with whimsical coral furniture in soft pinks and greens, glowing jellyfish serving as floating lanterns, sea glass windows filtering turquoise ocean light, gentle bubble streams rising along the walls, and a warm enchanting aquatic glow throughout',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'princess-mononoke-forest',
    name: 'Princess Mononoke Forest',
    description: 'Ancient Spirit Dwelling',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=400',
    prompt: 'Transform this room into the ancient forest spirit dwelling from Princess Mononoke, with massive moss-covered stones and roots forming walls, tiny glowing kodama tree spirits perched on branches, a crystal clear spring pool in the center, dappled primeval sunlight filtering through an ancient canopy, and a sacred untouched atmosphere',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
