module.exports = [
  {
    id: 'elden-ring-roundtable',
    name: 'Elden Ring Roundtable',
    description: 'Roundtable Hold',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform this room into the Roundtable Hold from Elden Ring, an ancient stone chamber centered around a massive round table scarred by centuries of battle. Embers drift lazily through melancholic golden light, Tarnished weapons and tattered banners line the walls, crumbling arches frame a dying fireplace, and an air of fading grandeur pervades every corner.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'god-of-war-norse-home',
    name: 'God of War Norse Home',
    description: "Kratos's Cabin",
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=400',
    prompt: "Transform this room into Kratos's rustic cabin in Midgard from God of War, built from heavy Norse timber with carved runes along the doorframes. A weapon rack displays the Leviathan Axe and Blades of Chaos, fur-covered beds sit in the corner, a stone hearth glows with low flames, and a snowy pine forest is visible through frosted windows.",
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'bioshock-rapture',
    name: 'BioShock Rapture',
    description: 'Underwater Art Deco',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?w=400',
    prompt: 'Transform this room into a lavish Art Deco lounge in the underwater city of Rapture from BioShock, dripping with 1960s luxury now in decay. Cracked glass domes reveal dark ocean depths, flickering neon signs advertise Plasmids, water leaks through buckling walls, brass fixtures tarnish, velvet furniture rots, and eerie blue-green light filters through everything.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'portal-test-chamber',
    name: 'Portal Test Chamber',
    description: 'Aperture Science',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    prompt: 'Transform this room into an Aperture Science test chamber from Portal, lined with sterile white modular panels and clean industrial edges. Glowing orange and blue portal marks shimmer on opposing walls, a Weighted Companion Cube sits on a button, an observation window reveals empty offices above, and harsh fluorescent light bathes the clinical space.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'skyrim-tavern',
    name: 'Skyrim Tavern',
    description: 'Nordic Inn',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400',
    prompt: 'Transform this room into a Nordic tavern from Skyrim, built from rough-hewn stone and dark timber beams. A roaring central hearth sends sparks upward, mead kegs and tankards line the bar, a bard plays lute in a candle-lit corner, animal pelts drape wooden benches, iron chandeliers hang from the ceiling, and warm amber firelight fills the hall.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'halo-unsc-bridge',
    name: 'Halo UNSC Bridge',
    description: 'Pillar of Autumn',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400',
    prompt: 'Transform this room into the command bridge of the Pillar of Autumn from Halo, a vast military deck with grey reinforced bulkheads and utilitarian UNSC design. Holographic tactical displays project fleet positions, a central command console glows blue, deep space and distant stars are visible through armored viewports, and overhead strip lighting casts cold sterile illumination.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'mass-effect-normandy',
    name: 'Mass Effect Normandy',
    description: "Captain's Cabin",
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=400',
    prompt: "Transform this room into Commander Shepard's captain's cabin aboard the SSV Normandy from Mass Effect, a sleek quarters with smooth curved walls and blue ambient lighting. A rotating galaxy map hologram glows on the desk, a glass case displays collectible model ships, a space hamster habitat sits nearby, and a panoramic skylight reveals swirling nebulae.",
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'assassins-creed-bureau',
    name: "Assassin's Creed Bureau",
    description: 'Renaissance Hideout',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1534759926787-89fa60cada61?w=400',
    prompt: 'Transform this room into a hidden Assassin bureau in Renaissance Florence from Assassin\'s Creed, accessed through a rooftop lattice entrance. Detailed maps and coded contracts cover the walls, a hidden blade workshop with tools and mechanisms occupies one corner, ornate Italian architecture frames arched windows, and warm candlelight illuminates Assassin insignias carved in stone.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'animal-crossing-home',
    name: 'Animal Crossing Home',
    description: 'Island Paradise',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400',
    prompt: 'Transform this room into a cozy cartoon island house from Animal Crossing, bursting with pastel colors and charming rounded furniture. A DIY workbench sits in the corner beside stacked crafting materials, fossil displays line the shelves, cheerful wallpaper and cute patterned rugs decorate the space, and bright sunshine pours through large sunny windows.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'hollow-knight-city',
    name: 'Hollow Knight City',
    description: 'City of Hallownest',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=400',
    prompt: 'Transform this room into the forgotten underground City of Tears in Hallownest from Hollow Knight, an ancient bug civilization carved from luminous stone. Bioluminescent blue fungi cast ethereal light on towering insectoid architecture, crystal formations jut from cracked floors, perpetual rain drips through the cavern ceiling, and a haunting melancholic beauty pervades the abandoned grandeur.',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
