module.exports = [
  {
    id: 'dubai-sky-penthouse',
    name: 'Dubai Sky Penthouse',
    description: '100th Floor Glass Tower',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400',
    prompt: 'Transform this room into a 100th-floor Dubai penthouse with floor-to-ceiling glass walls framing the Burj Khalifa at sunset, white Calacatta marble floors with gold inlay accents, a cantilevered infinity pool on the wraparound terrace, brushed gold fixtures, floating onyx kitchen island, and the glittering city skyline stretching to the Arabian Gulf below',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'monaco-yacht-interior',
    name: 'Monaco Yacht Interior',
    description: 'Superyacht Master Suite',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=400',
    prompt: 'Transform this room into a superyacht master suite moored in Monaco harbor with honey-toned teak paneling, cream white leather furnishings, panoramic curved ocean windows revealing the Riviera coastline, a built-in champagne bar with crystal stemware, polished brass nautical fittings, soft recessed lighting, and the gentle sway of Mediterranean luxury',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'tokyo-capsule-hotel',
    name: 'Tokyo Capsule Hotel',
    description: 'Ultra-Modern Capsule Pod',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=400',
    prompt: 'Transform this room into an ultra-modern Tokyo capsule hotel pod with seamless white molded walls, programmable LED ambient lighting shifting through calming hues, a built-in high-resolution screen display, minimalist recessed storage compartments, touch-panel climate controls, memory-foam sleeping platform, and the elegant Japanese efficiency of every centimeter perfectly utilized',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'scandinavian-hygge-cabin',
    name: 'Scandinavian Hygge Cabin',
    description: 'Norwegian Mountain Retreat',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=400',
    prompt: 'Transform this room into a cozy Norwegian mountain cabin radiating hygge warmth with golden pine-clad walls, draped sheepskin throws over deep armchairs, a crackling cast-iron wood stove glowing amber, clusters of flickering beeswax candles, hand-knit wool blankets, a steaming mug on a rustic side table, and heavy snowfall visible through frost-edged windows',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'moroccan-riad',
    name: 'Moroccan Riad',
    description: 'Traditional Courtyard Mansion',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1548018560-c7196e4f2859?w=400',
    prompt: 'Transform this room into a traditional Moroccan riad courtyard with intricate geometric zellige tilework in cobalt and emerald, a central marble fountain trickling softly, fragrant orange trees in terracotta pots, hand-carved plaster archways, jewel-toned silk cushions on cedar daybeds, brass lanterns casting latticed shadows, and warm North African sunlight flooding the open roof',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'bali-jungle-villa',
    name: 'Bali Jungle Villa',
    description: 'Open-Air Tropical Retreat',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400',
    prompt: 'Transform this room into an open-air Bali jungle villa with a vanishing-edge infinity pool overlooking terraced rice paddies, hand-carved volcanic stone walls, rich tropical teak and mahogany furnishings, a thatched alang-alang roof, lush jungle canopy pressing in with frangipani and orchids, and golden afternoon light filtering through towering palm fronds',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'swiss-alpine-chalet',
    name: 'Swiss Alpine Chalet',
    description: 'Luxury Ski Lodge',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1520984032042-162d526883e0?w=400',
    prompt: 'Transform this room into a luxury Swiss alpine chalet with a massive rough-hewn stone fireplace roaring with flame, antler chandeliers hanging from vaulted timber beams, panoramic floor-to-ceiling windows revealing snow-covered Alps peaks, plush sheepskin rugs on wide-plank oak floors, warm cognac leather seating, and the quiet grandeur of high-altitude winter elegance',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'nyc-soho-loft',
    name: 'NYC SoHo Loft',
    description: 'Industrial Converted Loft',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
    prompt: 'Transform this room into a converted SoHo industrial loft with exposed red brick walls, original cast-iron structural columns, polished concrete floors reflecting gallery-style track lighting, oversized factory windows framing the Manhattan skyline at dusk, mid-century modern furniture, large abstract canvases, and the raw sophisticated energy of downtown New York creative living',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'santorini-cave-house',
    name: 'Santorini Cave House',
    description: 'Cycladic Whitewashed Dwelling',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400',
    prompt: 'Transform this room into a Santorini cave house with smooth whitewashed plaster walls carved into the caldera cliff, arched alcoves holding flickering candles, natural volcanic stone accents, a private terrace overlooking iconic blue domes and the deep Aegean Sea, draped white linen curtains billowing in the breeze, and a blazing orange-pink sunset painting the sky',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'african-safari-lodge',
    name: 'African Safari Lodge',
    description: 'Luxury Tented Camp',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=400',
    prompt: 'Transform this room into a luxury African safari tented camp with heavy canvas walls rolled up to reveal the golden savanna, vintage campaign furniture in dark mahogany and leather, polished brass lanterns and telescope, a sundowner drinks bar with crystal decanters, Persian rugs on raised teak decking, and the warm amber glow of a setting sun silhouetting acacia trees',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
