module.exports = [
  {
    id: 'iss-space-station',
    name: 'ISS Space Station',
    description: 'Orbital Zero-Gravity Module',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400',
    prompt: 'Transform this room into a module of the International Space Station, with padded white walls lined with equipment racks, zero-gravity sleeping bags tethered to the wall, laptops and tools floating mid-air, tangled cable bundles, blinking control panels, and the luminous curve of Earth visible through the cupola window',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'moon-base-alpha',
    name: 'Moon Base Alpha',
    description: 'Lunar Colony Habitat',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?w=400',
    prompt: 'Transform this room into a lunar colony habitat on the Moon, with regolith-3D-printed curved grey-white walls, compact low-gravity furniture magnetically anchored to the floor, a glowing hydroponic garden shelf growing leafy greens, soft diffused LED lighting, and a wide viewport revealing the barren lunar surface with Earth rising on the horizon',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'underwater-research-lab',
    name: 'Underwater Research Lab',
    description: 'Deep Ocean Research Station',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=400',
    prompt: 'Transform this room into a deep ocean research station, with thick pressure-resistant dome windows revealing dark abyssal waters and bioluminescent jellyfish drifting past, banks of sonar monitors and scientific instruments, reinforced steel bulkheads with submarine-style hatches, cool blue ambient lighting, and specimen tanks filled with strange deep-sea organisms',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'steampunk-airship',
    name: 'Steampunk Airship',
    description: 'Victorian Dirigible Cabin',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1505672678657-cc7037095e60?w=400',
    prompt: 'Transform this room into the cabin of a Victorian steampunk dirigible, with polished brass navigation instruments and pressure gauges lining mahogany walls, exposed copper pipes hissing steam, tufted leather captain chairs, spinning clockwork gears behind glass panels, antique maps pinned to a corkboard, and billowing white clouds visible through riveted porthole windows',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'solarpunk-greenhouse',
    name: 'Solarpunk Greenhouse',
    description: 'Utopian Sustainable Home',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    prompt: 'Transform this room into a solarpunk utopian greenhouse home, with lush living walls overflowing with ferns and flowering vines, an elegant bamboo and reclaimed wood structure, transparent solar panels in the ceiling casting warm golden light, a rainwater collection system with visible glass pipes, handmade ceramic planters, and a serene atmosphere of harmony with nature',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'generation-ship-atrium',
    name: 'Generation Ship Atrium',
    description: 'Starship Central Park',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    prompt: 'Transform this room into the central atrium of a generation starship, with a vast artificial sky ceiling projecting soft daylight, tiered residential blocks rising along curved walls surrounding a lush communal green space, winding pathways through miniature parks and ponds, far-future community gathering areas, and the subtle hum of life-support systems sustaining a city among the stars',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'dyson-sphere-habitat',
    name: 'Dyson Sphere Habitat',
    description: 'Megastructure Interior',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400',
    prompt: 'Transform this room into the interior of a Dyson Sphere megastructure enclosing a star, with impossibly vast artificial landscapes curving upward in every direction, rivers and forests stretching across the inner shell, perpetual warm daylight from the captured sun at the center, towering advanced-civilization architecture, and a breathtaking sense of incomprehensible scale',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'terraform-mars-dome',
    name: 'Terraform Mars Dome',
    description: 'Mars Colony Greenhouse',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=400',
    prompt: 'Transform this room into an early Mars colony greenhouse dome, with orange-tinted natural light filtering through a transparent pressure dome, rows of hydroponic growing racks bursting with green crops, the rusty red Martian landscape stretching beyond the glass, compact pioneer living quarters with recycled materials, dust-coated airlocks, and a resilient frontier spirit',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'quantum-lab',
    name: 'Quantum Lab',
    description: 'Quantum Computing Laboratory',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    prompt: 'Transform this room into a cutting-edge quantum computing laboratory, with towering supercooled quantum processors visible behind frosted glass chambers trailing wisps of condensation, holographic data visualizations floating above sleek consoles, sterile white clean-room surfaces, blue ultraviolet decontamination lighting, and an atmosphere of silent groundbreaking scientific discovery',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'cyberpunk-hacker-den',
    name: 'Cyberpunk Hacker Den',
    description: 'Underground Digital Hideout',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400',
    prompt: 'Transform this room into an underground cyberpunk hacker den, with an entire wall covered in mismatched glowing monitors displaying scrolling code and surveillance feeds, tangled nests of cables spilling across the floor, neon pink and cyan LED strips casting harsh shadows, scattered energy drink cans and takeout boxes, a battered ergonomic chair, and a rebellious digital anarchist aesthetic',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];
