const worlds = [
  // ============ CINEMATIC — ICONIC MOVIE LOCATIONS ============
  {
    id: 'jurassic-park-lab',
    name: 'Jurassic Park Lab',
    description: 'InGen Genetics Lab',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400',
    prompt: 'Transform this room into the InGen genetics laboratory from Jurassic Park with rows of glowing amber-preserved mosquito specimens in backlit display cases, humming DNA sequencing machines with scrolling double-helix readouts, translucent embryo storage tanks filled with blue-green fluid, stainless steel lab benches cluttered with petri dishes and pipettes, lush tropical ferns pressing against rain-streaked floor-to-ceiling windows, and cool fluorescent overhead lighting casting clinical white reflections on polished tile floors',
    price: 0,
    isProOnly: false,
    isFeatured: true,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'shining-overlook-hotel',
    name: 'The Shining Overlook Hotel',
    description: 'Room 237 Terror',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
    prompt: 'Transform this room into the Overlook Hotel from The Shining featuring the iconic hexagonal orange and brown carpet pattern stretching down an impossibly long symmetrical corridor, heavy gold and burnt-orange 1970s drapes flanking dark wooden doorframes, twin matching table lamps on polished side tables, antique brass elevator doors at the corridor end, eerie warm tungsten lighting creating unsettling shadows, faded floral wallpaper in muted olive and mustard tones, and an oppressive atmosphere of frozen-in-time retro grandeur',
    price: 0,
    isProOnly: false,
    isFeatured: true,
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'back-to-future-garage',
    name: 'Back to the Future Garage',
    description: "Doc Brown's Workshop",
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400',
    prompt: 'Transform this room into Doc Brown\'s cluttered garage laboratory from Back to the Future with scattered flux capacitor components and wiring diagrams pinned to corkboards, DeLorean blueprints and time circuit schematics taped to concrete walls, overflowing workbenches covered in soldering irons and oscilloscopes, stacks of 1985 newspapers and pizza boxes, a wall of mismatched clocks all showing different times, tangled cables hanging from exposed ceiling joists, and harsh bare-bulb workshop lighting casting sharp shadows across greasy tools and spare car parts',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'mad-max-war-rig',
    name: 'Mad Max War Rig',
    description: 'Post-Apocalyptic Ride',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400',
    prompt: 'Transform this room into the interior of a Mad Max Fury Road war rig with heavily riveted rusted steel wall panels streaked with desert sand patina, cracked and sun-bleached leather seats held together with crude stitching, chrome skulls and exhaust pipes repurposed as decorative elements, makeshift gauges and hand-welded instrument panels, chains and heavy canvas straps hanging from exposed roll-cage framework, gritty orange-amber light filtering through dusty slit windows revealing endless desert wasteland outside, and every surface worn raw by sand and sun',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'inception-dream-room',
    name: 'Inception Dream Room',
    description: 'Impossible Architecture',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=400',
    prompt: 'Transform this room into an Inception-style dream space with M.C. Escher-inspired impossible architecture where staircases loop endlessly upward and doorways open onto ceilings, furniture attached to walls and ceilings defying gravity, a folding cityscape visible through massive windows where skyscrapers curl upward like pages of a book, polished concrete and glass surfaces reflecting infinite recursive patterns, cool steel-blue and warm amber lighting coexisting in impossible shadow directions, and a surreal stillness suggesting the fragile boundary between dream layers',
    price: 0,
    isProOnly: false,
    isFeatured: true,
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'grand-budapest-hotel',
    name: 'Grand Budapest Hotel',
    description: 'Wes Anderson Charm',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    prompt: 'Transform this room into the Grand Budapest Hotel lobby with perfectly symmetrical Wes Anderson composition, soft pink and lilac pastel walls adorned with gilded Art Deco moldings, an ornate brass elevator with a diamond-patterned gate at center frame, polished checkerboard marble floors in rose and cream, a grand mahogany concierge desk with brass call bells and tiny cubbyholes for room keys, velvet upholstered lobby chairs in plum and mauve, crystal chandeliers casting warm rosy light, and every element precisely centered with obsessive visual balance',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'john-wick-continental',
    name: 'John Wick Continental',
    description: 'Assassin Luxury Club',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1564078516393-cf04bd966897?w=400',
    prompt: 'Transform this room into the Continental Hotel lounge from John Wick with floor-to-ceiling dark mahogany wood paneling polished to a mirror sheen, deep oxblood leather Chesterfield club chairs arranged around low marble-topped cocktail tables, brushed gold accent lighting from Art Deco wall sconces casting warm amber pools, a long onyx bar backed by shelves of top-shelf spirits in crystal decanters, subtle geometric gold inlays in black marble flooring, heavy velvet curtains in midnight navy, and an atmosphere of refined menace where elegance masks lethal purpose',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'fifth-element-apartment',
    name: 'Fifth Element Apartment',
    description: 'Futuristic NYC Flat',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400',
    prompt: 'Transform this room into Korben Dallas\'s tiny futuristic apartment from The Fifth Element with compact modular living space where a bed folds into the wall and an automated kitchen dispenses instant meals from a sleek panel, warm orange and yellow plastic surfaces contrasting with brushed aluminum fixtures, a cluttered bedside table with a retro-futuristic alarm clock and scattered cigarettes, a narrow window revealing a vertical cityscape of flying taxi cabs weaving between impossibly tall neon-lit skyscrapers, smoggy golden sunset light filtering through grimy glass, and a lived-in chaos within hyper-efficient design',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'guardians-galaxy-ship',
    name: 'Guardians of the Galaxy Ship',
    description: 'Retro-Futuristic Cruiser',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400',
    prompt: 'Transform this room into the Milano spaceship interior from Guardians of the Galaxy with a retro-futuristic cockpit featuring worn leather pilot seats, mismatched control panels covered in toggle switches and flickering analog gauges, a vintage cassette tape player mounted on the dashboard alongside alien navigation holographs, warm orange cockpit lighting mixed with cool blue instrument glow, exposed conduit wiring and duct-taped repairs on hull panels, a backdrop of deep purple and pink nebula visible through the curved windshield, and scattered personal items from a ragtag crew who call this junker home',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'black-panther-wakanda',
    name: 'Black Panther Wakanda',
    description: 'Vibranium Throne Room',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=400',
    prompt: 'Transform this room into the Wakandan throne room from Black Panther with soaring carved stone walls inlaid with glowing vibranium-blue circuit-like veins, a magnificent panther-shaped throne carved from dark basalt and accented with luminous purple vibranium ore, sweeping tribal textile tapestries in rich earth tones of terracotta and indigo featuring bold geometric Adinkra patterns, floating holographic displays projecting Wakandan data scripts in translucent blue, massive floor-to-ceiling windows revealing a hidden high-tech African metropolis, warm amber sunlight blending with cool vibranium glow, and ceremonial Dora Milaje spear racks flanking the royal dais',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 9,
    isActive: true,
  },
];

module.exports = worlds;
