const worlds = [
  // ============ NATURE & FANTASY WORLDS ============
  {
    id: 'treehouse-paradise',
    name: 'Treehouse Paradise',
    description: 'Luxury Rainforest Retreat',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400',
    prompt: 'Transform this room into a luxury treehouse high in an ancient rainforest canopy with live-edge hardwood floors, rope bridge walkways between platforms, glass floor sections revealing misty jungle below, carved wooden railings entwined with flowering vines, tropical birds on branch-framed windowsills, dappled golden sunlight through emerald leaves, and rattan furniture draped in linen',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'ice-palace',
    name: 'Ice Palace',
    description: 'Frozen Aurora Throne Room',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1517783999520-f068d7431571?w=400',
    prompt: 'Transform this room into a frozen palace with towering carved ice walls in fractal frost patterns, a crystal ceiling revealing green and violet aurora borealis overhead, a grand ice throne refracting blue-white light, translucent ice columns lining a polished frozen floor, icicle chandeliers casting prismatic fragments, and an ethereal cold glow radiating from within the walls',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'crystal-cave-home',
    name: 'Crystal Cave Home',
    description: 'Amethyst Geode Dwelling',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1504699439244-a4b5e56c0708?w=400',
    prompt: 'Transform this room into living quarters inside a giant amethyst crystal cave with geode walls of deep purple and lavender formations reflecting violet light, natural mineral shelves holding candles, a stone-carved bed cushioned with furs, quartz side tables glowing from within, stalactites overhead, and warm amber lantern light mingling with cool purple crystalline radiance',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'volcano-lair',
    name: 'Volcano Lair',
    description: 'Secret Volcanic Fortress',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1462651567147-aa679fd1cfaf?w=400',
    prompt: 'Transform this room into a secret villain lair inside a dormant volcano with glass floor panels revealing molten lava rivers below, polished black obsidian walls reflecting dramatic crimson light, a steel command console overlooking the caldera, brutalist pillars with red LED strips, a suspended catwalk spanning the magma chamber, and smoldering ember glow in deep volcanic reds',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'cloud-city',
    name: 'Cloud City',
    description: 'Floating Sky Pavilion',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=400',
    prompt: 'Transform this room into a floating city above the clouds with white marble terraces and open-air pavilions supported by elegant columns, golden sunlight over polished stone floors, silver and crystal wind chimes swaying in gentle breezes, billowing cloud banks visible through arched colonnades, trailing wisteria on rooftop gardens, and a panoramic sky vista stretching to a glowing horizon',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'mushroom-kingdom',
    name: 'Mushroom Kingdom',
    description: 'Giant Bioluminescent Fungi Home',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1504198266287-1659872e6590?w=400',
    prompt: 'Transform this room into a giant mushroom house interior with softly glowing bioluminescent caps forming the domed ceiling in turquoise and amber, cozy oversized fairy-tale furniture with toadstool stools and acorn-cap bowls, spongy moss forest floor carpet, shelf fungus wall shelves, dangling spore-light lanterns, and bark-framed round windows overlooking an enchanted twilight woodland',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'fairy-garden-cottage',
    name: 'Fairy Garden Cottage',
    description: 'Enchanted Miniature Manor',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1459767129954-1b1c1f9b9ace?w=400',
    prompt: 'Transform this room into a magical fairy cottage scaled for humans with flower petal lampshades casting rosy light, dewdrop crystal chandeliers, lush moss carpet wall to wall, acorn-shell furniture and twig-framed mirrors, walls woven from living willow branches with wildflowers, cobweb-lace curtains on round windows, and soft golden firefly light drifting through the air',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'dragons-treasury',
    name: "Dragon's Treasury",
    description: 'Ancient Hoard Chamber',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform this room into a dragon\'s treasure hoard cave with mountains of gleaming gold coins and jeweled goblets across the cavern floor, scattered rubies and emeralds catching firelight, ancient runed swords propped against scale-textured stone walls, smoldering ember light from cracks in volcanic rock, claw marks gouged into pillars, and smoky haze drifting near the vaulted ceiling',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'mermaid-grotto',
    name: 'Mermaid Grotto',
    description: 'Underwater Sea Cave Dwelling',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=400',
    prompt: 'Transform this room into an underwater mermaid grotto with pearl-encrusted cave walls shimmering in aquamarine light, living coral furniture in pink and orange formations, flowing kelp curtains swaying in gentle currents, bioluminescent fish as floating lanterns casting blue-green glow, a giant clamshell bed lined with silk, sea glass mosaic floors, and rippling caustic light patterns from the ocean above',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'phoenix-nest-aerie',
    name: 'Phoenix Nest Aerie',
    description: 'Mountain-Top Rebirth Chamber',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=400',
    prompt: 'Transform this room into a phoenix nest aerie atop a mountain peak with walls woven from shimmering golden and crimson feathers, amber crystals in volcanic rock alcoves, a central fire bowl with eternal rebirth flames in orange and gold, panoramic arches revealing sunrise over cloud-wrapped mountains, ash motes floating upward, and warm light in tones of molten copper',
    price: 0,
    isProOnly: false,
    isFeatured: false,
    sortOrder: 0,
    isActive: true,
  },
];

module.exports = worlds;
