require('dotenv').config();
const mongoose = require('mongoose');
const SpecialtyWorld = require('../src/models/SpecialtyWorld');

const worlds = [
  // ============ FANTASY ============
  {
    id: 'hobbit-hole',
    name: 'Hobbit Hole',
    description: 'Middle Earth Style',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform this room into a cozy Hobbit hole from the Shire with a perfectly round green door, warm wood-paneled circular rooms, a roaring fireplace with a kettle, copper pots hanging from beams, overstuffed armchairs, a well-stocked pantry visible, and warm golden lamplight',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'gryffindor-room',
    name: 'Gryffindor Common Room',
    description: 'Bravery & Gold',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    prompt: 'Transform this room into the Gryffindor common room in the tower with plush scarlet armchairs by a crackling fireplace, gold and crimson tapestries, a notice board, warm Persian rugs, leaded glass windows overlooking the grounds, and cozy reading nooks',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'slytherin-dungeon',
    name: 'Slytherin Common Room',
    description: 'Ambition & Green',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400',
    prompt: 'Transform this room into the Slytherin common room beneath the Black Lake with green-tinted light filtering through underwater windows, dark leather sofas, silver and green tapestries, ornate serpent carvings on stone pillars, and a roaring emerald-flame fireplace',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'hogwarts-great-hall',
    name: 'Hogwarts Great Hall',
    description: 'Enchanted Feasts',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400',
    prompt: 'Transform this room into the Hogwarts Great Hall with floating candles above long wooden tables, enchanted ceiling showing the night sky, house banners hanging from stone walls, and warm golden candlelight illuminating Gothic arched windows',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'dumbledores-office',
    name: "Dumbledore's Office",
    description: 'Headmaster Tower',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400',
    prompt: "Transform this room into Dumbledore's office at Hogwarts with circular tower room, Pensieve on a table, Fawkes the phoenix perch, spinning silver instruments, portraits of former headmasters on walls, and the Sorting Hat on a shelf",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'room-of-requirement',
    name: 'Room of Requirement',
    description: 'Whatever You Need',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform this room into the Room of Requirement from Harry Potter, a magical space that shifts to your needs — filled with towering stacks of hidden objects, mysterious artifacts, vanishing cabinets, and warm ambient magical glow',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'hogwarts-library',
    name: 'Hogwarts Library',
    description: 'Ancient Knowledge',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400',
    prompt: 'Transform this room into the Hogwarts library with towering bookshelves reaching cathedral ceilings, floating candles, restricted section behind iron gates, wooden study tables with green reading lamps, and ancient leather-bound spell books',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'potions-classroom',
    name: 'Potions Classroom',
    description: 'Dungeon Brewing',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400',
    prompt: "Transform this room into Snape's potions classroom in the Hogwarts dungeons with bubbling cauldrons, shelves of glass jars containing mysterious ingredients, stone walls with flickering torchlight, and a blackboard with potion recipes",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'winterfell-great-hall',
    name: 'Winterfell Great Hall',
    description: 'House Stark Castle',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400',
    prompt: "Transform this room into Winterfell's Great Hall with massive stone walls, direwolf banners, a long wooden feast table, iron chandeliers, fur-draped chairs, and a roaring hearth large enough to stand in",
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'iron-throne-room',
    name: 'Iron Throne Room',
    description: 'Kings Landing Palace',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=400',
    prompt: 'Transform this room into the Iron Throne room at the Red Keep with the towering throne of melted swords, tall stained glass windows, dragon skull decorations, polished stone floors, and imposing Lannister crimson banners',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'dragonstone-castle',
    name: 'Dragonstone Castle',
    description: 'Targaryen Seat',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?w=400',
    prompt: "Transform this room into Dragonstone castle's war room with the painted table of Westeros, dragon-shaped braziers, black volcanic stone walls, narrow windows overlooking a stormy sea, and Targaryen three-headed dragon banners",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'castle-black',
    name: 'Castle Black',
    description: "Night's Watch Fortress",
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400',
    prompt: "Transform this room into Castle Black at the Wall with rough-hewn timber halls, blazing iron fire pits, Night's Watch black banners, fur cloaks on hooks, and narrow windows showing an icy landscape beyond the Wall",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'highgarden',
    name: 'Highgarden',
    description: 'House Tyrell Castle',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
    prompt: 'Transform this room into Highgarden castle with elegant rose motifs, sunlit chambers with flowing curtains, garden views through arched windows, golden Tyrell decorations, and lush green ivy climbing stone walls',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'upside-down',
    name: 'The Upside Down',
    description: 'Stranger Things Dimension',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1509248961895-b23aad4f24b4?w=400',
    prompt: 'Transform this room into The Upside Down from Stranger Things — a dark mirror dimension with floating ash particles, bio-organic vine tendrils covering walls and ceiling, cold blue-grey atmosphere, decaying furniture, and an eerie bioluminescent glow',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'jedi-temple',
    name: 'Jedi Temple',
    description: 'Force Meditation Chamber',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?w=400',
    prompt: 'Transform this room into a Jedi Temple meditation chamber with tall marble columns, serene natural light filtering through geometric windows, minimalist stone benches, holocron display cases, and the peaceful glow of kyber crystals',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'narnia-wardrobe',
    name: 'Narnia Beyond Wardrobe',
    description: 'Magical Winter Forest',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=400',
    prompt: 'Transform into Narnia just beyond the wardrobe',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Gaming - Minecraft
  {
    id: 'minecraft-castle',
    name: 'Minecraft Castle',
    description: 'Transform into a Minecraft-inspired castle interior with blocky stone walls, pixelated textures, torch lighting on walls, crafting table, enchantment room with bookshelves, and diamond block accents',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1577741314755-048d8525d31e?w=400',
    prompt: 'Transform into a Minecraft-inspired castle interior with blocky stone walls, pixelated textures, torch lighting on walls, crafting table, enchantment room with bookshelves, and diamond block accents',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Gaming - Zelda
  {
    id: 'zelda-temple',
    name: 'Zelda Temple of Time',
    description: 'Transform into the Temple of Time from The Legend of Zelda with sacred stone pedestals, ethereal light beaming through stained glass windows depicting the Triforce, marble floors, and the Master Sword pedestal',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    prompt: 'Transform into the Temple of Time from The Legend of Zelda with sacred stone pedestals, ethereal light beaming through stained glass windows depicting the Triforce, marble floors, and the Master Sword pedestal',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: TV - Wednesday
  {
    id: 'wednesday-nevermore',
    name: 'Nevermore Academy',
    description: 'Transform into Nevermore Academy from Wednesday with dark Gothic architecture, stained glass windows, wrought iron chandeliers, taxidermy displays, stone corridors with flickering candles, and a macabre academic atmosphere',
    category: 'fantasy',
    imageUrl: 'https://images.unsplash.com/photo-1509248961895-b23aad4f24b4?w=400',
    prompt: 'Transform into Nevermore Academy from Wednesday with dark Gothic architecture, stained glass windows, wrought iron chandeliers, taxidermy displays, stone corridors with flickering candles, and a macabre academic atmosphere',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ CINEMATIC ============
  {
    id: 'hollywood-glamour',
    name: 'Hollywood Glamour',
    description: 'Golden Age Luxury',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    prompt: 'Transform into 1940s Hollywood glamour style',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'hawkins-80s-basement',
    name: 'Hawkins 80s Basement',
    description: 'Retro Gaming Den',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400',
    prompt: 'Transform this room into Mike Wheeler\'s 1980s Hawkins basement with wood-paneled walls, a Dungeons & Dragons table setup, walkie-talkies, an old CRT TV with Atari, superhero posters, a plaid couch, and warm incandescent lighting',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'starcourt-mall',
    name: 'Starcourt Mall',
    description: '80s Shopping Center',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1519567241046-7f570f88e07a?w=400',
    prompt: 'Transform this room into the Starcourt Mall from Stranger Things Season 3 with 1980s neon signage, colorful storefronts, terrazzo floors, bright fluorescent lighting, a food court with plastic chairs, and retro pop culture displays',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'hoppers-cabin',
    name: "Hopper's Cabin",
    description: 'Woodland Hideout',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=400',
    prompt: 'Transform this room into Jim Hopper\'s cabin in the woods from Stranger Things with rustic log walls, a cozy cluttered interior, trip-wire alarm system at the door, flannel blankets, a small TV, canned food supplies, and warm amber lamplight',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'hawkins-lab',
    name: 'Hawkins Lab',
    description: 'Government Facility',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400',
    prompt: 'Transform this room into Hawkins National Laboratory with sterile white corridors, fluorescent tube lighting, observation windows, scientific equipment, metal examination tables, and an ominous government facility atmosphere',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'wes-anderson-hotel',
    name: 'Grand Budapest Hotel',
    description: 'Wes Anderson Aesthetic',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=400',
    prompt: 'Transform into a Wes Anderson film set, Grand Budapest Hotel style',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'titanic-first-class',
    name: 'Titanic First Class',
    description: '1912 Ocean Liner',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
    prompt: 'Transform into a Titanic first-class suite',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // Existing TV Series - cinematic
  {
    id: 'breaking-bad-lab',
    name: 'Breaking Bad Superlab',
    description: 'Transform into Walter White\'s superlab from Breaking Bad with industrial stainless steel equipment, chemical apparatus, bright white fluorescent lighting, yellow hazmat suits hanging, and pristine laboratory conditions',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400',
    prompt: 'Transform into Walter White\'s superlab from Breaking Bad with industrial stainless steel equipment, chemical apparatus, bright white fluorescent lighting, yellow hazmat suits hanging, and pristine laboratory conditions',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'peaky-blinders-office',
    name: 'Shelby Company Office',
    description: 'Peaky Blinders',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400',
    prompt: 'Transform into Thomas Shelby office from Peaky Blinders',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'money-heist-hideout',
    name: 'La Casa de Papel Hideout',
    description: 'Transform into the Professor\'s hideout from Money Heist with maps and blueprints covering every wall, multiple monitors showing security feeds, Dalí masks on shelves, red jumpsuits hanging, and meticulous planning boards',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1550439062-609e1531270e?w=400',
    prompt: 'Transform into the Professor\'s hideout from Money Heist with maps and blueprints covering every wall, multiple monitors showing security feeds, Dalí masks on shelves, red jumpsuits hanging, and meticulous planning boards',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'squid-game-dorm',
    name: 'Squid Game Dorm',
    description: 'Korean Survival Game',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1541123603104-512919d6a96c?w=400',
    prompt: 'Transform into Squid Game player dormitory',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'friends-apartment',
    name: "Monica's Apartment",
    description: 'Central Perk NYC',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    prompt: 'Transform into Monica Geller apartment from Friends',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'narcos-mansion',
    name: 'Escobar Hacienda',
    description: 'Narcos Drug Lord Style',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
    prompt: 'Transform into Pablo Escobar Hacienda from Narcos',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'sherlock-baker-street',
    name: '221B Baker Street',
    description: 'BBC Sherlock',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    prompt: 'Transform into 221B Baker Street from BBC Sherlock',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Gaming - Resident Evil
  {
    id: 'resident-evil-mansion',
    name: 'Spencer Mansion',
    description: 'Transform into the Spencer Mansion from Resident Evil with Victorian gothic grandeur, a grand staircase, marble floors with the Umbrella logo, dim chandelier lighting, and an unsettling elegance hiding dark secrets',
    category: 'cinematic',
    imageUrl: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=400',
    prompt: 'Transform into the Spencer Mansion from Resident Evil with Victorian gothic grandeur, a grand staircase, marble floors with the Umbrella logo, dim chandelier lighting, and an unsettling elegance hiding dark secrets',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ FUTURISTIC ============
  {
    id: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    description: 'Neon Night City',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400',
    prompt: 'Transform this room into a Cyberpunk 2077 Night City megabuilding apartment with floor-to-ceiling holographic windows showing a neon skyline, modular smart furniture, LED strip lighting in cyan and magenta, exposed tech panels, and a weapons rack on the wall',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'post-apocalyptic',
    name: 'Post-Apocalyptic',
    description: 'Bunker Survival',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1534854638093-bada1813ca19?w=400',
    prompt: 'Transform into post-apocalyptic bunker hideout',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'mars-colony',
    name: 'Mars Colony',
    description: 'Red Planet Base',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=400',
    prompt: 'Transform into Mars colony habitat module',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'cyber-tokyo',
    name: 'Cyber-Tokyo',
    description: 'Neon Metropolis',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400',
    prompt: 'Transform into futuristic Tokyo apartment',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'futuristic-ship',
    name: 'Futuristic Ship',
    description: 'Sci-Fi Interior',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=400',
    prompt: 'Transform into futuristic spaceship interior',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'matrix-construct',
    name: 'Matrix Construct',
    description: 'White Loading Room',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400',
    prompt: 'Transform this room into The Matrix Construct — an infinite white void loading program with a minimalist white floor stretching to infinity, weapon racks materializing, and a single leather chair in the center with green digital code faintly visible',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'nebuchadnezzar-ship',
    name: 'Nebuchadnezzar Ship',
    description: 'Matrix Hovercraft',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    prompt: 'Transform this room into the Nebuchadnezzar hovercraft interior with exposed metal grating floors, industrial pipes, dim red emergency lighting, operator chair stations with green-scrolling monitors, and worn crew quarters with hammocks',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'matrix-club-hel',
    name: 'Club Hel',
    description: 'Merovingian Club',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400',
    prompt: 'Transform this room into Club Hel from Matrix Reloaded with deep red velvet seating, gothic chandeliers, reflective black marble floors, cage-like metalwork, moody purple and red neon lighting, and an underground bunker atmosphere',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'neo-apartment',
    name: "Neo's Apartment",
    description: 'Hacker Den',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1550439062-609e1531270e?w=400',
    prompt: 'Transform this room into Neo\'s apartment from The Matrix — a dark cluttered hacker den with multiple CRT monitors, tangled cables, dark walls covered in newspaper clippings, a record player, dim green-tinted lighting, and a sense of digital paranoia',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'zion',
    name: 'Zion',
    description: 'Underground City',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=400',
    prompt: 'Transform this room into Zion\'s living quarters from The Matrix with carved rock walls, warm orange torchlight, woven textiles, industrial metal staircases, communal gathering spaces, and a raw underground city aesthetic',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'millennium-falcon',
    name: 'Millennium Falcon',
    description: 'Star Wars Smuggler Ship',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=400',
    prompt: 'Transform this room into the Millennium Falcon\'s main hold and lounge with the holochess table, curved white corridor walls, exposed wiring and mechanical panels, blue-lit cockpit glow, worn leather seats, and smuggler\'s storage compartments',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'tatooine-home',
    name: 'Tatooine Homestead',
    description: 'Desert Dwelling',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=400',
    prompt: 'Transform this room into Luke Skywalker\'s underground homestead on Tatooine with curved adobe walls, a sunken circular courtyard visible above, moisture vaporator parts on shelves, desert-toned furnishings, and twin sunset light streaming in',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'death-star',
    name: 'Death Star Interior',
    description: 'Imperial Station',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=400',
    prompt: 'Transform this room into a Death Star command center with angular black and grey Imperial architecture, glowing control panels, circular viewport showing space, TIE fighter bay visible below, and harsh overhead lighting',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'naboo-palace',
    name: 'Naboo Palace',
    description: 'Royal Elegance',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1577083288073-40892c0860a4?w=400',
    prompt: 'Transform this room into the Naboo Royal Palace with ornate Renaissance-inspired architecture, domed ceilings with painted murals, cascading water features, warm terracotta and gold tones, flowing curtains, and lake views through arched windows',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'mos-eisley-cantina',
    name: 'Mos Eisley Cantina',
    description: 'Wretched Hive',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400',
    prompt: 'Transform this room into the Mos Eisley Cantina from Star Wars with a curved bar, dim moody lighting, exotic alien-themed decor, booth seating with worn leather, desert sandstone walls, and a small stage for the band',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'blade-runner-2049',
    name: 'Blade Runner 2049',
    description: 'Neo-Noir Future',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400',
    prompt: 'Transform into a Blade Runner 2049 apartment',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'tron-grid',
    name: 'Tron Grid',
    description: 'Digital Light World',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=400',
    prompt: 'Transform into Tron digital grid world',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'interstellar-endurance',
    name: 'Endurance Ship',
    description: 'Transform into the Endurance spacecraft from Interstellar with circular rotating habitat modules, NASA-functional design, small crew quarters, observation windows showing Saturn\'s rings, and the clinical beauty of deep space exploration',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1534996858221-380b92700493?w=400',
    prompt: 'Transform into the Endurance spacecraft from Interstellar with circular rotating habitat modules, NASA-functional design, small crew quarters, observation windows showing Saturn\'s rings, and the clinical beauty of deep space exploration',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Sci-Fi - Dune
  {
    id: 'dune-arrakis',
    name: 'Arrakis Palace',
    description: 'Transform into a Fremen sietch on Arrakis from Dune with desert sandstone cave chambers, stillsuit storage, spice-amber lighting, carved rock walls, moisture reclamation systems, and woven desert tapestries',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=400',
    prompt: 'Transform into a Fremen sietch on Arrakis from Dune with desert sandstone cave chambers, stillsuit storage, spice-amber lighting, carved rock walls, moisture reclamation systems, and woven desert tapestries',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Sci-Fi - Alien
  {
    id: 'alien-nostromo',
    name: 'Nostromo Ship',
    description: 'Transform into the USCSS Nostromo from Alien with cramped industrial corridors, dripping condensation, green CRT terminal screens, hypersleep chambers, chain-link walkways, and oppressive low-ceiling claustrophobic atmosphere',
    category: 'futuristic',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400',
    prompt: 'Transform into the USCSS Nostromo from Alien with cramped industrial corridors, dripping condensation, green CRT terminal screens, hypersleep chambers, chain-link walkways, and oppressive low-ceiling claustrophobic atmosphere',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ HISTORICAL ============
  {
    id: 'victorian-1800s',
    name: '1800s Victorian',
    description: 'Gothic Elegance',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=400',
    prompt: 'Transform this room into an opulent Victorian parlor from the 1800s with dark mahogany wainscoting, William Morris wallpaper patterns, a marble fireplace with ornate mantel clock, tufted velvet chaise lounge, crystal chandelier, heavy brocade curtains, and gas lamp lighting',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'stone-age',
    name: '8000 BC Stone Age',
    description: 'Primitive Living',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
    prompt: 'Transform into Stone Age dwelling',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'egyptian-palace',
    name: 'Egyptian Palace',
    description: "Pharaoh's Court",
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400',
    prompt: "Transform this room into an Ancient Egyptian pharaoh's throne room with massive sandstone columns covered in hieroglyphics, gold leaf ceiling details, lotus flower motifs, lapis lazuli and turquoise inlays, burning incense braziers, and the throne of Tutankhamun",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'medieval-castle',
    name: 'Medieval Castle',
    description: 'Stone Fortress',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?w=400',
    prompt: 'Transform into medieval castle chamber',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'mayan-temple',
    name: 'Mayan Temple',
    description: 'Jungle Ruins',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=400',
    prompt: 'Transform into Mayan temple chamber',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'gatsby-mansion',
    name: 'Gatsby Mansion',
    description: 'Roaring 1920s Party',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400',
    prompt: 'Transform into The Great Gatsby mansion party room',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'roman-villa',
    name: 'Roman Villa',
    description: 'Ancient Empire Luxury',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400',
    prompt: 'Transform into an Ancient Roman villa',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'ottoman-harem',
    name: 'Ottoman Palace',
    description: 'Topkapi Elegance',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=400',
    prompt: 'Transform into an Ottoman palace chamber from Topkapi',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'renaissance-studio',
    name: 'Renaissance Studio',
    description: 'Da Vinci Workshop',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1577720580479-7d839d829c73?w=400',
    prompt: "Transform into a Renaissance artist studio like Leonardo da Vinci's workshop",
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'bridgerton-regency',
    name: 'Bridgerton Drawing Room',
    description: 'Regency Era Romance',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    prompt: 'Transform into a Bridgerton Regency era drawing room',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  // NEW: TV - Peaky Blinders Pub
  {
    id: 'peaky-blinders-pub',
    name: 'Garrison Pub',
    description: 'Transform into the Garrison pub from Peaky Blinders with dark wood paneling, etched glass partitions, brass fixtures, a long mahogany bar, gas lamps, and 1920s Birmingham working-class atmosphere',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400',
    prompt: 'Transform into the Garrison pub from Peaky Blinders with dark wood paneling, etched glass partitions, brass fixtures, a long mahogany bar, gas lamps, and 1920s Birmingham working-class atmosphere',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Architecture - Bauhaus
  {
    id: 'bauhaus-studio',
    name: 'Bauhaus Studio',
    description: 'Transform into a 1920s Bauhaus design studio with primary color accents, tubular steel furniture, geometric shapes, industrial windows, typography posters, and the clean functionalism of Walter Gropius',
    category: 'historical',
    imageUrl: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400',
    prompt: 'Transform into a 1920s Bauhaus design studio with primary color accents, tubular steel furniture, geometric shapes, industrial windows, typography posters, and the clean functionalism of Walter Gropius',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ NATURE ============
  {
    id: 'prehistoric-cave',
    name: 'Prehistoric Cave',
    description: 'Natural Shelter',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=400',
    prompt: 'Transform into prehistoric cave dwelling',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'underwater-atlantis',
    name: 'Underwater Atlantis',
    description: 'Deep Sea Kingdom',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400',
    prompt: 'Transform this room into an underwater Atlantean palace chamber with translucent coral walls, bioluminescent jellyfish lighting, pearl-inlaid furniture, flowing water features, ocean views through dome windows, and ancient Greek-inspired underwater architecture',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'japanese-zen',
    name: 'Japanese Zen',
    description: 'Temple Peace',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=400',
    prompt: 'Transform into Japanese Zen temple space',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'nordic-hall',
    name: 'Nordic Hall',
    description: 'Viking Longhouse',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400',
    prompt: 'Transform into Viking longhouse great hall',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'pandora-hometree',
    name: 'Pandora Hometree',
    description: "Avatar Na'vi Dwelling",
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c036bc3e69?w=400',
    prompt: "Transform into a Na'vi Hometree dwelling from Avatar",
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'enchanted-forest-cabin',
    name: 'Enchanted Forest',
    description: 'Fairy Tale Cottage',
    category: 'nature',
    imageUrl: 'https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=400',
    prompt: 'Transform into an enchanted forest fairy tale cottage',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ LUXURY ============
  {
    id: 'tsunami-shelter',
    name: 'Tsunami Shelter',
    description: 'Disaster Proof',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    prompt: 'Transform into high-tech tsunami shelter',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'belle-epoque',
    name: 'Belle Epoque',
    description: 'Parisian Charm',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=400',
    prompt: 'Transform into Belle Epoque Parisian salon',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'dubai-penthouse',
    name: 'Dubai Sky Penthouse',
    description: 'Ultra Luxury Living',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    prompt: 'Transform into an ultra-luxury Dubai penthouse',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'the-crown-palace',
    name: 'Buckingham Palace',
    description: 'The Crown Royal Style',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400',
    prompt: 'Transform into a Buckingham Palace state room from The Crown',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'succession-penthouse',
    name: 'Roy Family Penthouse',
    description: 'Succession Billionaire',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    prompt: 'Transform into the Roy family penthouse from Succession',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Architecture - Fallingwater
  {
    id: 'frank-lloyd-wright',
    name: 'Fallingwater House',
    description: 'Transform into Frank Lloyd Wright\'s Fallingwater with cantilevered terraces over a waterfall, natural stone walls, open floor plan merging with forest, horizontal lines, and organic architecture in harmony with nature',
    category: 'luxury',
    imageUrl: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=400',
    prompt: 'Transform into Frank Lloyd Wright\'s Fallingwater with cantilevered terraces over a waterfall, natural stone walls, open floor plan merging with forest, horizontal lines, and organic architecture in harmony with nature',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ ANIMATED ============
  {
    id: 'simpsons-living-room',
    name: 'Simpsons Living Room',
    description: 'Springfield Home',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=400',
    prompt: 'Transform into The Simpsons living room from Springfield',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'family-guy-house',
    name: 'Griffin Family Room',
    description: 'Quahog Residence',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
    prompt: 'Transform into the Griffin family living room from Family Guy',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'rick-morty-garage',
    name: "Rick's Garage Lab",
    description: 'Mad Scientist Workshop',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=400',
    prompt: 'Transform into Rick Sanchez garage laboratory from Rick and Morty',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'death-note-room',
    name: 'Light Yagami Room',
    description: 'Death Note Anime',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    prompt: 'Transform into Light Yagami bedroom from Death Note anime',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'spirited-away-bathhouse',
    name: 'Spirited Away Bathhouse',
    description: 'Studio Ghibli Magic',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1528164344705-47542687000d?w=400',
    prompt: 'Transform into the bathhouse from Spirited Away by Studio Ghibli',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'attack-titan-headquarters',
    name: 'Survey Corps HQ',
    description: 'Attack on Titan',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1533154683836-84ea7a0bc310?w=400',
    prompt: 'Transform into Survey Corps headquarters from Attack on Titan',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'demon-slayer-dojo',
    name: 'Demon Slayer Dojo',
    description: 'Kimetsu no Yaiba',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=400',
    prompt: 'Transform into a Demon Slayer Corps training dojo',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'south-park-room',
    name: 'South Park Bedroom',
    description: 'Colorado Kids',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    prompt: 'Transform into a South Park kids bedroom',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'adventure-time-treehouse',
    name: 'Finn & Jake Treehouse',
    description: 'Land of Ooo',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1520637836993-a071674a97c4?w=400',
    prompt: 'Transform into Finn and Jake treehouse from Adventure Time',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Anime - Spirited Away (new enhanced version with different id)
  {
    id: 'spirited-away',
    name: 'Spirited Away Bathhouse',
    description: 'Transform into the magical bathhouse from Spirited Away with ornate Japanese architecture, steaming baths, paper lanterns, wooden walkways over water, and Yubaba\'s office visible above',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1528164344885-47b852f56fd7?w=400',
    prompt: 'Transform into the magical bathhouse from Spirited Away with ornate Japanese architecture, steaming baths, paper lanterns, wooden walkways over water, and Yubaba\'s office visible above',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Anime - Totoro
  {
    id: 'totoro-forest',
    name: "Totoro's Forest Home",
    description: 'Transform into the magical forest from My Neighbor Totoro with giant camphor tree hollow, soft moss floor, tiny Totoro creatures, magical dust motes floating in sunbeams, and a cozy nature-made shelter',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400',
    prompt: 'Transform into the magical forest from My Neighbor Totoro with giant camphor tree hollow, soft moss floor, tiny Totoro creatures, magical dust motes floating in sunbeams, and a cozy nature-made shelter',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Anime - Evangelion
  {
    id: 'evangelion-nerv',
    name: 'NERV Headquarters',
    description: 'Transform into NERV HQ from Evangelion with massive underground geo-front, orange hexagonal displays, command bridge terminals, LCL-filled corridors, and dramatic red emergency lighting',
    category: 'animated',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400',
    prompt: 'Transform into NERV HQ from Evangelion with massive underground geo-front, orange hexagonal displays, command bridge terminals, LCL-filled corridors, and dramatic red emergency lighting',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },

  // ============ CULTURAL ============
  {
    id: 'korean-hanok',
    name: 'Korean Hanok House',
    description: 'Traditional Seoul Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1590912710484-739e9ad9c7d3?w=400',
    prompt: 'Transform into a traditional Korean Hanok house',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'korean-modern-kdrama',
    name: 'K-Drama Penthouse',
    description: 'Seoul Luxury Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400',
    prompt: 'Transform into a modern Korean drama penthouse',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'turkish-modern',
    name: 'Istanbul Chic',
    description: 'Modern Turkish Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    prompt: 'Transform into modern Turkish Istanbul style',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'turkish-konak',
    name: 'Anatolian Konak',
    description: 'Ottoman Mansion',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=400',
    prompt: 'Transform into a traditional Turkish konak mansion',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'italian-tuscan',
    name: 'Tuscan Villa',
    description: 'Italian Countryside',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400',
    prompt: 'Transform into an Italian Tuscan villa',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'italian-milan-modern',
    name: 'Milan Design District',
    description: 'Contemporary Italian',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400',
    prompt: 'Transform into a Milan design district apartment',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'greek-santorini',
    name: 'Santorini Blue',
    description: 'Greek Island Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400',
    prompt: 'Transform into a Santorini Greek island home',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'greek-classical',
    name: 'Classical Athens',
    description: 'Ancient Greek Temple',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=400',
    prompt: 'Transform into an Ancient Greek classical interior',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'french-parisian',
    name: 'Parisian Apartment',
    description: 'Haussmann Elegance',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=400',
    prompt: 'Transform into a classic Parisian Haussmann apartment',
    isFeatured: true,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'french-provence',
    name: 'Provence Farmhouse',
    description: 'French Country Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400',
    prompt: 'Transform into a French Provence farmhouse',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'spanish-andalusian',
    name: 'Andalusian Riad',
    description: 'Moorish Spanish Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=400',
    prompt: 'Transform into a Spanish Andalusian interior',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'moroccan-riad',
    name: 'Marrakech Riad',
    description: 'Moroccan Palace',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=400',
    prompt: 'Transform into a Moroccan riad in Marrakech',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'indian-mughal',
    name: 'Mughal Palace',
    description: 'Royal Indian Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400',
    prompt: 'Transform into a Mughal palace chamber',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'scandinavian-hygge',
    name: 'Nordic Hygge',
    description: 'Cozy Scandinavian',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400',
    prompt: 'Transform into a Scandinavian hygge living space',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'mexican-hacienda',
    name: 'Mexican Hacienda',
    description: 'Vibrant Latin Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
    prompt: 'Transform into a Mexican hacienda',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'brazilian-tropical',
    name: 'Rio Tropical Modern',
    description: 'Brazilian Beach Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400',
    prompt: 'Transform into a Brazilian tropical modern home',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'chinese-traditional',
    name: 'Ming Dynasty Chamber',
    description: 'Imperial Chinese',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400',
    prompt: 'Transform into a Ming Dynasty Chinese chamber',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'russian-imperial',
    name: 'St. Petersburg Palace',
    description: 'Tsarist Russian Style',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400',
    prompt: 'Transform into a Russian Imperial palace chamber',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  {
    id: 'balinese-resort',
    name: 'Bali Paradise Villa',
    description: 'Indonesian Tropical',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=400',
    prompt: 'Transform into a Balinese villa resort',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
  // NEW: Architecture - Japanese Ryokan
  {
    id: 'japanese-ryokan',
    name: 'Traditional Ryokan',
    description: 'Transform into a traditional Japanese ryokan inn with tatami mat floors, futon bedding, shoji paper screens, an alcove with ikebana flower arrangement, a private onsen bath view, and serene minimalist tranquility',
    category: 'cultural',
    imageUrl: 'https://images.unsplash.com/photo-1545083036-b175dd155a1d?w=400',
    prompt: 'Transform into a traditional Japanese ryokan inn with tatami mat floors, futon bedding, shoji paper screens, an alcove with ikebana flower arrangement, a private onsen bath view, and serene minimalist tranquility',
    isFeatured: false,
    price: 0,
    isProOnly: false,
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  await SpecialtyWorld.deleteMany({});
  console.log('Cleared existing worlds');

  const result = await SpecialtyWorld.insertMany(worlds);
  console.log(`Inserted ${result.length} worlds`);

  // Print summary by category
  const categories = await SpecialtyWorld.aggregate([
    { $group: { _id: '$category', count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]);
  console.log('\nBy category:');
  categories.forEach((c) => console.log(`  ${c._id}: ${c.count}`));

  console.log(`\nTotal worlds: ${result.length}`);

  await mongoose.disconnect();
  console.log('Disconnected from MongoDB');
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
