const mongoose = require('mongoose');

const specialtyWorldSchema = new mongoose.Schema({
  id: {
    type: String,
    required: true,
    unique: true,
  },
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  category: {
    type: String,
    enum: ['fantasy', 'historical', 'futuristic', 'cinematic', 'nature', 'luxury', 'animated', 'cultural', 'sci-fi', 'retro', 'home'],
    required: true,
  },
  // Legacy single-size URL (often still an Unsplash or `thumbnails/<id>.jpg`).
  // Kept for backward compatibility with older app builds that read `imageUrl`.
  imageUrl: {
    type: String,
    required: true,
  },
  // CloudFront thumbnail (512) generated by scripts/generate-thumbnails-batch.
  // New Flutter clients prefer this over `imageUrl`.
  thumbnailUrl: {
    type: String,
  },
  // Bumped when the world's thumbnails are regenerated; appended as ?v=<n>.
  imageVersion: {
    type: Number,
    default: 1,
  },
  prompt: {
    type: String,
    required: true,
  },
  // How this template should treat the user's existing room when generating:
  //   'transform' → fully redesign / restyle the room into the template's theme
  //                 (themed worlds, full style packs, room sections).
  //   'preserve'  → keep the room's existing design, furniture, layout and style
  //                 exactly as-is and apply ONLY the single described change
  //                 (quick tools like Add Plants / Sunset, functional tweaks).
  // Drives prompt enrichment in falService.generatePrompt — see promptEnrichment.js.
  designIntent: {
    type: String,
    enum: ['transform', 'preserve'],
    default: 'transform',
  },
  price: {
    type: Number,
    default: 0.99,
  },
  isProOnly: {
    type: Boolean,
    default: false, // If true, only available for pro users for free
  },
  isFeatured: {
    type: Boolean,
    default: false,
  },
  sortOrder: {
    type: Number,
    default: 0,
  },
  isActive: {
    type: Boolean,
    default: true,
  },
}, {
  timestamps: true,
});

// Index for faster queries
specialtyWorldSchema.index({ category: 1, sortOrder: 1 });
specialtyWorldSchema.index({ isActive: 1, isFeatured: -1 });
specialtyWorldSchema.index({ name: 'text', description: 'text', id: 'text' });

module.exports = mongoose.model('SpecialtyWorld', specialtyWorldSchema);

